"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { supabase } from "../../../lib/supabase";

type Answer={id:string;question_id:string;user_id:string|null;body:string;created_at:string;edited:boolean;like_count?:number;liked?:boolean;profiles?:{nickname:string}|null};
type Question={id:string;user_id:string|null;qualification_id:string;title:string;body:string;created_at:string;updated_at:string;edited:boolean;profiles?:{nickname:string}|null;qualifications?:{name:string}|null};
const demoQuestion:Question={id:"demo-1",user_id:null,qualification_id:"",title:"二級建築士の受験資格について教えてください",body:"高校生のうちから準備するとしたら、まず何を勉強するのがおすすめですか？",created_at:new Date().toISOString(),updated_at:new Date().toISOString(),edited:false,profiles:{nickname:"建築を勉強中"},qualifications:{name:"二級建築士"}};
const demoAnswers:Answer[]=[{id:"demo-a1",question_id:"demo-1",user_id:null,body:"まずは公式の受験資格を確認して、学校で学んでいる建築の基礎をしっかり身につけるのがおすすめです。",created_at:new Date().toISOString(),edited:false,like_count:12,profiles:{nickname:"建築経験者"}},{id:"demo-a2",question_id:"demo-1",user_id:null,body:"過去問を見て、どの分野が出題されるのかを把握してから勉強計画を立てると進めやすいです。",created_at:new Date().toISOString(),edited:false,like_count:8,profiles:{nickname:"二級建築士"}}];
export default function QuestionDetail(){const {id}=useParams<{id:string}>(); const [q,setQ]=useState<Question|null>(null);const [answers,setAnswers]=useState<Answer[]>([]);const [text,setText]=useState("");const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");const [userId,setUserId]=useState<string|null>(null);
 useEffect(()=>{(async()=>{if(!supabase){setQ(demoQuestion);setAnswers(demoAnswers);setLoading(false);return;} const {data:{user}}=await supabase.auth.getUser();setUserId(user?.id||null);const {data,error}=await supabase.from("questions").select("id,user_id,qualification_id,title,body,created_at,updated_at,edited,profiles(nickname),qualifications(name)").eq("id",id).is("deleted_at",null).single(); if(error||!data){setMessage("この質問は見つかりませんでした。");setLoading(false);return;} setQ(data as any);const {data:ans}=await supabase.from("answers").select("id,question_id,user_id,body,created_at,edited,profiles(nickname)").eq("question_id",id).is("deleted_at",null); if(ans){const ids=ans.map(a=>a.id);const {data:likes}=await supabase.from("likes").select("target_id,user_id").eq("target_type","answer").in("target_id",ids.length?ids:["00000000-0000-0000-0000-000000000000"]);const mapped=(ans as any[]).map(a=>{const ls=(likes||[]).filter((l:any)=>l.target_id===a.id);return {...a,like_count:ls.length,liked:!!user&&ls.some((l:any)=>l.user_id===user.id)}}).sort((a,b)=>(b.like_count||0)-(a.like_count||0));setAnswers(mapped);}setLoading(false);})()},[id]);
 const bestId=useMemo(()=>answers.length?answers[0].id:null,[answers]);
 async function postAnswer(){setMessage("");if(!text.trim())return;if(!supabase){setMessage("Supabase未接続のため、現在はデモ表示です。");return;}if(!userId){setMessage("回答するにはログインしてください。");return;}const {data,error}=await supabase.from("answers").insert({question_id:id,user_id:userId,body:text.trim()}).select("id,question_id,user_id,body,created_at,edited,profiles(nickname)").single();if(error){setMessage(error.message);return;}setAnswers([...answers,{...(data as any),like_count:0,liked:false}]);setText("");setMessage("回答を投稿しました。");}
 async function toggleLike(a:Answer){if(!supabase||!userId){setMessage("👍役に立ったを使うにはログインしてください。");return;}const target={user_id:userId,target_type:"answer",target_id:a.id};if(a.liked){const {error}=await supabase.from("likes").delete().match(target);if(error){setMessage(error.message);return;}setAnswers(answers.map(x=>x.id===a.id?{...x,liked:false,like_count:Math.max(0,(x.like_count||0)-1)}:x).sort((x,y)=>(y.like_count||0)-(x.like_count||0)));}else{const {error}=await supabase.from("likes").insert(target);if(error){setMessage(error.message);return;}setAnswers(answers.map(x=>x.id===a.id?{...x,liked:true,like_count:(x.like_count||0)+1}:x).sort((x,y)=>(y.like_count||0)-(x.like_count||0)));}}
 if(loading)return <div className="wrap section"><div className="empty">読み込み中…</div></div>; if(!q)return <div className="wrap section"><div className="notice">{message||"質問が見つかりませんでした。"}</div><Link href="/questions" className="btn" style={{display:"inline-block",marginTop:14}}>質問広場へ戻る</Link></div>;
 return <div className="wrap section detail"><Link href="/questions" className="muted">← 質問広場へ戻る</Link><div className="card" style={{marginTop:14}}><span className="pill">#{q.qualifications?.name||"資格"}</span><h1 className="big">{q.title}</h1><p style={{whiteSpace:"pre-wrap",lineHeight:1.8}}>{q.body}</p><span className="muted">{q.profiles?.nickname||"ユーザー"}　{new Date(q.created_at).toLocaleDateString("ja-JP")}{q.edited?"　編集済み":""}</span></div>
 <h2 style={{marginTop:32}}>回答 {answers.length}</h2>{message&&<div className="notice" style={{marginBottom:14}}>{message}</div>}<div className="list">{answers.map((a,i)=><div className="card" key={a.id}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><span className="pill">{a.id===bestId?"ベストアンサー":"回答"}</span><span className="muted">{a.profiles?.nickname||"ユーザー"}</span></div><p style={{whiteSpace:"pre-wrap",lineHeight:1.8}}>{a.body}</p><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span className="muted">{new Date(a.created_at).toLocaleDateString("ja-JP")}{a.edited?"　編集済み":""}</span><button className={a.liked?"btn":"btn light"} onClick={()=>toggleLike(a)}>👍 役に立った {a.like_count||0}</button></div></div>)}</div>
 <div className="card form" style={{marginTop:20}}><h3>回答する</h3><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="経験や知識をもとに回答してください"/><button className="btn" onClick={postAnswer}>回答を投稿</button><p className="muted">回答の「役に立った」が最も多いものをベストアンサーとして表示します。</p></div></div>;
}
